// src/actions/types.js

export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_FAILURE = 'FETCH_CONTACTS_FAILURE';

export const POST_CONTACTS_REQUEST = 'POST_CONTACT_REQUEST';
export const POST_CONTACTS_SUCCESS = 'POST_CONTACTS_SUCCESS';
export const POST_CONTACTS_FAILURE = 'POST_CONTACTS_FAILURE';

export const EDIT_CONTACTS_REQUEST = 'EDIT_CONTACT_REQUEST';
export const EDIT_CONTACTS_SUCCESS = 'EDIT_CONTACTS_SUCCESS';
export const EDIT_CONTACTS_FAILURE = 'EDIT_CONTACTS_FAILURE';

export const DELETE_CONTACTS_REQUEST = 'DELETE_CONTACT_REQUEST';
export const DELETE_CONTACTS_SUCCESS = 'DELETE_CONTACTS_SUCCESS';
export const DELETE_CONTACTS_FAILURE = 'DELETE_CONTACTS_FAILURE';
